### PR TITLE
Add automated benchmarking using AWS

### PR DESCRIPTION
**Pull request by jasonifiedz**
Please follow the steps in README for verification.

The steps are similar to the GCP ones except that AWS requires using ECR (Elastic Container Registry) as the registry.

### CODE REVIEW

**Review by polymorpher — APPROVED** [review]
looks good, thanks

**Comment by polymorpher** [comment]
I fixed a few small issues, see https://github.com/delendum-xyz/zk-benchmarking/compare/9ccca360335a14f3fb7b81a748aed7710dc1e67d...cd7995eb28cf47a85b0ba952c9878845bf7314e9

In the latest RISC0 updates (not sure if it is change in dependency packages or based on code introduced in https://github.com/delendum-xyz/zk-benchmarking/pull/30), RISC0 toolchain (see link in my comment to that PR) needs to be installed before RISC0 benchmark can be built, otherwise it would show this error:

```
  --- stderr
  The 'risc0' toolchain could not be found.
  To install the risc0 toolchain, use cargo-risczero.
  For example:
    cargo install cargo-risczero
    cargo risczero install
warning: build failed, waiting for other jobs to finish...
```

Can you update the tool accordingly for both GCP and AWS?

Also RISC0 benchmark now requires an output file parameter, and dumps all the results to the file instead of stdout

**Comment by jasonifiedz** [comment]
Sounds good. I'll update these in the next few days.

Best,
Jason Zhao

**Comment by polymorpher** [comment]
The instances also don't self-terminate, which could add a lot of expensive billing

**Comment by jasonifiedz** [comment]
That’s weird. It did when I first wrote it. I’ll check that tonight.

Best,
Jason Zhao

**Comment by jasonifiedz** [comment]
I was able to get past the " The 'risc0' toolchain could not be found."
error by running the following commands:
cargo install cargo-risczero
cargo risczero install

but there's another issue: https://justpaste.it/cp2qk.

This error happens locally and when I run the benchmarking in AWS. Is there
a domain expert on risczero that can help on this?

Best,
Jason Zhao

**Pull request merged**
